### ISSUE TITLE
Problem With month day  

### ISSUE THREAD

**Issue by jugalbalara** [mmick66/KDCalendarView#2]
Month day not show all days of month

**Comment by EduardRakov** [comment]
What do you mean?

**Comment by jonaseduardo** [comment]
There is a Bug in the class KDCalendarViewMonthCell.m

replace: 

shouldDisplayAsActive &= indexPath.item >= _firstDayActive && indexPath.item <= _lastDayActive

for

shouldDisplayAsActive &= indexPath.item >= _firstDayActive && indexPath.item <= _lastDayActive + _firstWeekdayOfMonthIndex - 1;

**Comment by mmick66** [comment]
Could you please add it as a pull request? I will review and merge.

**Comment by jaiminios** [comment]
How to start date selection from current date?
because currently it start with one day ago from current date

**Comment by bayraa1992** [comment]
there has a bug with in shown active days of month correctly. I solved this problem with one few line code on KDCalendarViewMonthCell.m. Here is code 

`    BOOL shouldDisplayAsActive = NO;

    if (_firstWeekdayOfMonthIndex <= indexPath.item  && indexPath.item  < _firstWeekdayOfMonthIndex + _numberOfDaysInMonth) {
        shouldDisplayAsActive = YES;
    }
    dayCell.isCurrentMonth = shouldDisplayAsActive;
`

**Comment by mmick66** [comment]
Thank you very much! Can you please do a pull request with this code?
