### ISSUE TITLE
NSURLConnection failing after using calendar view

### ISSUE THREAD

**Issue by pragnareddye** [mmick66/KDCalendarView#3]
In the form-type project that we're building JSON requests are made to fetch different portions of the form in swift. We have merged the calendar project into it (Objective-C into swift) and using it to select multiple dates. On completion of the load of the calendar view, no further NSURLConnection requests can be made. We have tested it by bypassing the calendar view and it's working, but just letting the calendar view load makes all further requests in the application fail.

**Comment by mmick66** [comment]
That is very strange. Are you sure that the UI does not freeze entirely?

**Comment by pragnareddye** [comment]
Thank you for replying . It is now fixed . As soon as calender view is entered  the event threads began to run continously blocking other threads .

**Comment by mmick66** [comment]
Was it a problem with the code or the specific implementation? Is there something I need to be aware of?

**Comment by pragnareddye** [comment]
The problem was with the implementation.  That calendar is amazing.  Thank
you

**Comment by mmick66** [comment]
Haha! Thanks... I do not know about amazing but I tried. Enjoy.
